server:
    port: 8080
spring:
    application:
        name: database to excel
    profiles:
        active:
            - "dev"
    datasource:
        url: jdbc:postgresql://localhost:5432/psql_to_excel
        username: alliano-dev
        password: alliano361**
        hikari:
            connection-timeout: 600000
            idle-timeout: 600000
            max-lifetime: 180000
            maximum-pool-size: 10
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialec: org.hibernate.dialec.PostgreSQLDialec
                '[format_sql]': true
                # enable batch insert
                jdbc:
                    '[order_insert]': true
                    '[batch_size]': 500
logging:
  level:
    root: INFO
    '[org.springframework.data.*.*]': trace
    '[org.springframework.cache.*]': trace
